/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateSplImport } from './routes/create-spl'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreateSplRoute = CreateSplImport.update({
  id: '/create-spl',
  path: '/create-spl',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-spl': {
      id: '/create-spl'
      path: '/create-spl'
      fullPath: '/create-spl'
      preLoaderRoute: typeof CreateSplImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-spl': typeof CreateSplRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-spl': typeof CreateSplRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-spl': typeof CreateSplRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-spl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-spl'
  id: '__root__' | '/' | '/create-spl'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateSplRoute: typeof CreateSplRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateSplRoute: CreateSplRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-spl"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-spl": {
      "filePath": "create-spl.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
